### ISSUE TITLE
Cursors broken for functions.

### ISSUE THREAD

**Issue by tolmasky** [dustingetz/react-cursor#19]
Took me hours to figure out, but the following won't work:

// Over consecutive calls...
mycursor.refine("whatever").set(new Function("console.log(" + i + ")") 

From what I can see poking around the code, functions don't really seem to figure into the hashing system for the memorizer very well. The strange construction in the above code (new function) is just to show that even when there is not toString equivalence it is still failing. Over consecutive calls the functions will be log(1), log(2), log(3), etc. However, Cursor.build(this) still returns the original log(1) version. If I remove the memorizer factory, everything starts working again.

**Comment by dustingetz** [comment]
Closing this as we have no plans to support storing non-value types in cursors - will address with better documentation in #48
