### ISSUE TITLE
What does the refine method do? 

### ISSUE THREAD

**Issue by ezmiller** [dustingetz/react-cursor#36]
Hi, I am new to the cursor concept and have not used Om yet, but I like very much the general idea and think it it looks very useful when dealing with data in React. I'm not entirely clear, however, what the refine method is doing. It would be great if you could provide (at your leisure of course) any more documentation/explanation about what the refine method is doing. It seems quite central. 

Thanks for this great library.

**Comment by danielmiladinov** [comment]
The refine function takes one or more strings representing the "path" into a subtree of the cursor's value, and returns another Cursor whose value is just that subtree.

Consider: pretend the following `state` to be the state of your component:

```javascript
var state = {
  a: {
    alice: "is a nice person",
    foo: {
      susan: [4, 5, 6]
    }
  },
  b: {
    bar: {
      bob: "likes blue things",
      charlie: [1, 2, 3]
    }
  }
};
```
You could take the cursor that was bound to your component's state, and call `cursor.refine('b', 'bar')` on it. That would return the subtree you get from walking the path, `['b', 'bar']`. On this fictitious state value, the subtree at `['b', 'bar']` is the following:

```javascript
var refined = {
  bob: "likes blue things",
  charlie: [1, 2, 3]
};
```

[We presented react and an earlier version of react-cursor][1] at QCon last year; you could fast-forward to 39:50, where we demonstrate some of the capabilities of cursors.

[1]: http://www.infoq.com/presentations/fp-facebook-react

**Comment by ezmiller** [comment]
@danielmiladinov thank you! This was what I needed to know. Some explanation along these lines in the docs might be a great help to others.
