### ISSUE TITLE
Use of the word "orthoganal" in docs

### ISSUE THREAD

**Issue by ezmiller** [dustingetz/react-cursor#41]
As with programming, it is usually a good idea in language to use the simplest possible solution. Is there a way to communicate what is meant by orthogonal with a more easily understood word? Do you mean that react-cursor and Flux represents opposite approaches?

**Comment by dustingetz** [comment]
Not opposite, not sure what word to use, here is what orthogonal means in software: http://codebetter.com/jeremymiller/2007/01/09/orthogonal-code/

how would you word it?

**Comment by dustingetz** [comment]
http://www.artima.com/intv/dry3.html

**Comment by ezmiller** [comment]
It seems to me on a quick reading of these documents that "orthogonality" -- a very clumsy word -- is being used to indicate a certain approach to software architecture. The first one you linked described it as an approach that favors "loose coupling and high cohesion." These concepts are already much more specific, but themselves still very abstract. 

Given that "orthogonality" is such an umbrella terms, I am really not sure what words I would choose. I'm not sure yet what you mean, for example, when you say: "The decision of stateful vs stateless components is orthogonal to Flux architecture." Can you perhaps explain this a bit more plainly? 

I am curious because I am developing that implements a version of Flux architecture, but upon discovering your wonderful library here, I started moving toward setting the state on the applications' top-level component `App`, then building a react-cursor from the component's state, and sending the cursor's refined values down into the child components. 

I wasn't sure, however, that I actually need a cursor for this. Why not, for instance, just send the values as standard props? 

Anyway, I'm happy to suggest an alternate wording, if you could help me understand a bit more what yu meant.

**Comment by ezmiller** [comment]
Thanks for those links as well; they look great!

**Comment by dustingetz** [comment]
Cursors let downtree views think in terms of a state subtree instead of the global app state as a whole. If you're using a state-at-top approach (as advocated by this library), your state values get deeply nested quickly and you need some mechanism for a downtree view to think in terms of only the state it cares about.

>  "The decision of stateful vs stateless components is orthogonal to Flux architecture." Can you perhaps explain this a bit more plainly?

Flux is about uni-directional data flow, and cursors are about state-at-top. You can structure your app using one or both or neither, they are separate concerns. Is that more clear wording?

**Comment by ezmiller** [comment]
Yes, I think that is much clearer. When I glanced over those documents that you sent around, it occurred to me that you might also just mean that react-cursor can work well alongside a Flux architecture because it encapsulates a distinct set of problems and solutions -- i.e. removing state from one's app -- whereas you say Flux is about uni-directional flow. 

Based on what you said, I think one thing that that section on Flux could use is just a simple statement that react-cursor can work well with Flux for the reason that you stated: "Flux is about uni-directional data flow, and cursors are about state-at-top." But I get the sense, maybe, that what you also want to emphasize is that react-cursor can be helpful on its own because it removes state. 

So something like:

```
React-cursor can be used fruitfully alongside Flux. Flux is about uni-directional data flow, and cursors are about state-at-top. Using the two together can be good in certain cases, where you need to simplify the flow of data, and you want to ensure as well that state information is quickly and deeply nested into the UI.
```

Still don't  know if I've understood you correctly to be more specific than that. Just riffing here a bit. 

One question I have about the idea that using a cursor makes things "stateless." In what sense is this true, given that the properties change, and thus still have state?

**Comment by dustingetz** [comment]
Your riff is accurate, I'll think about it some and update the readme, thanks.

Cursors do not make an app stateless, but they let an app keep all its state in a single place - thus the root view is stateful, and all downtree views are stateless. So cursors are a tool for reducing the surface area of code that is stateful.

**Comment by ezmiller** [comment]
> Cursors do not make an app stateless, but they let an app keep all its state in a single place - thus the root view is stateful, and all downtree views are stateless. So cursors are a tool for reducing the surface area of code that is stateful.

Wonderful explanation!
