### ISSUE TITLE
Do you forget to check in example/helloworld/webapp/js folder?

### ISSUE THREAD

**Issue by lijunle** [dustingetz/react-cursor#42]

**Comment by dustingetz** [comment]
No, There is a build step

**Comment by lijunle** [comment]
But, for the second example, the built js is provided.

**Comment by lijunle** [comment]
I think you miss the `js/Page.js` file.

**Comment by dustingetz** [comment]
https://github.com/dustingetz/react-cursor/commit/d8ba35632599311c10823348a0629f93826eccf3

**Comment by dustingetz** [comment]
Yes, thank you.
