### ISSUE TITLE
Avoid using React internal APIs.

### ISSUE THREAD

**Issue by lijunle** [dustingetz/react-cursor#43]
In the [`update` method](https://github.com/dustingetz/react-cursor/blob/master/src/Cursor.js#L40), you are using `cmp._reactInternalInstance._pendingStateQueue` to get the latest state.

Actually, React provide a `setState` override accepting function as the first argument to access the latest state. (Its logic is [here](https://github.com/facebook/react/blob/6a92179d6fd6d7c4097f6310a7cefb2c0651287f/src/renderers/shared/reconciler/ReactCompositeComponent.js#L604))

```js
function update(cmp, path, operation, nextValue) {
  this.setState(function (state) {
    if (path.length > 0) {
      return React.addons.update(
        state,
        path.concat(operation).reduceRight(util.unDeref, nextValue)
      );
    } else if (path.length === 0) {
      return nextValue;
    }
  });
}
```

*PS.* the current implementation prohibits the root component has its own state. Otherwise, the latest state in queue might be a partial object and not meet the unDeref operations.

**Comment by dustingetz** [comment]
This is published to npm and bower as v1.1.0
