### ISSUE TITLE
Readme is out of date

### ISSUE THREAD

**Issue by dustingetz** [dustingetz/react-cursor#48]
* pendingValue api is removed
* updater methods have new preferred updaterFunction api

**Comment by dustingetz** [comment]
Also docs to prevent #47

**Comment by dustingetz** [comment]
document #19

**Comment by dustingetz** [comment]
document https://github.com/dustingetz/react-cursor/issues/30

**Comment by lijunle** [comment]
document for [mutation issue](https://github.com/dustingetz/react-cursor/issues/49#issuecomment-124868968), may also related to #56 .

**Comment by dustingetz** [comment]
advantages over immutable-js and baobab:

1/ simpler types: use regular react state with plain old js data structures, 2/ simpler implementation - about 100 lines of code and tiny api, 3/ super easy to integrate with your existing large codebase already using react state

**Comment by dustingetz** [comment]
and https://github.com/mquan/cortex, are there others?
