### ISSUE TITLE
Can we detect and warn on out-of-band mutations?

### ISSUE THREAD

**Issue by dustingetz** [dustingetz/react-cursor#54]
Prevents #47. I'm not entirely convinced that it's possible to detect out-of-band mutations. I haven't thought it all the way through.

One idea, is that the cursor update methods (set, push, etc.) can hang on to a reference to the final value right before they pass it to react setState. Then in each subsequent invocation to a cursor update method, we can recursively check that the current cursor.value is reference-equal to the previous value at all nodes of the tree, before performing the update. This would have performance implications.

**Comment by dustingetz** [comment]
Background reading: https://github.com/facebook/react/issues/1753

**Comment by dustingetz** [comment]
Can we deep freeze react state? https://github.com/stample/atom-react/blob/master/src/utils/deepFreeze.js

**Comment by dustingetz** [comment]
We could also use Object.observe (recursively - so implement deepObserve)

**Comment by dustingetz** [comment]
@ezmiller, do you want to take a whack at an Object.freeze approach? We need to account for browser support, what can be polyfilled, and whether an O.freeze or O.observe or other approach is best.

**Comment by ezmiller** [comment]
Sorry, I've been away, but will catch up with all this soon.

**Comment by dustingetz** [comment]
O.O is looking pretty dead now https://esdiscuss.org/topic/an-update-on-object-observe

**Comment by lijunle** [comment]
I look into the code of React. They just [shadow freeze](https://github.com/facebook/react/blob/0b29035484f428cb56e7e1c04a88f66ac020d1d4/src/isomorphic/classic/element/ReactElement.js#L104) the `element.props`, as said in [its document](https://github.com/facebook/react/blob/401e6f10587b09d4e725763984957cf309dfdc30/docs/_posts/2015-02-24-streamlining-react-elements.md#solution-immutable-props).

However, there is a way to do [deep freeze](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze#Examples) mentioned in MDN examples.

@dustingetz Which option do you prefer? Shadow or deep?

**Comment by dustingetz** [comment]
I prefer deep, and since we only need to re-freeze the leaf subtree that comes out of react.addons.update, i dont think it will be that slow either.

**Comment by dustingetz** [comment]
re-open for 2.0

**Comment by dustingetz** [comment]
Merged into 2.0 (now master)
