### ISSUE TITLE
Implement old pendingValue api as stop-gap?

### ISSUE THREAD

**Issue by dustingetz** [dustingetz/react-cursor#57]
This is not necessary if we implement https://github.com/dustingetz/react-cursor/issues/53.

I'm working with a client who uses react-cursor, and some of their code broke with the React 13 upgrade because it relied on pendingValue. The new setState api is insufficient because they need to run effects with the pending value, and state updater fns are supposed to be pure, so there is no way to run an effect based on the pending value. [This pattern](https://gist.github.com/dustingetz/b9bb7f8202fc0d93c719) fixes the problem, but some large codebases don't want to rewrite their code. The wingspan codebase also comes to mind as reliant on pendingValue.

**Comment by lijunle** [comment]
I vote for the #53 solution.
