### ISSUE TITLE
Deprecate and remove apply function

### ISSUE THREAD

**Issue by lijunle** [dustingetz/react-cursor#59]
\cc @dustingetz @danielmiladinov 

After [this change](https://github.com/dustingetz/react-cursor/commit/d4491fb509a9648a1572a29b9a119e198bad9e5b#diff-f9b3da4de5b1f0fbdd8ab24842ce0412), the usage syntax for `apply` function looks weird.

Are we going to deprecated/remove this API?

**Comment by dustingetz** [comment]
I think so - .apply is now just the same as .set, right?

**Comment by lijunle** [comment]
Yes, the following two code snippets do the same thing exactly:

```js
a.apply(function (prevState) {
  return function (x) { return x / 8 }
});
```

```js
a.set(function (x) {
  return x / 8;
});
```

**Comment by dustingetz** [comment]
@ezmiller, here's a low hanging fruit PR if you want a warmup task!

**Comment by dustingetz** [comment]
The 2.0 changes to decouple from react impact this issue in ways that were not obvious to me. This will need to be thought through more deeply and resolved. There's currently a failing test ("apply against store") demonstrating the problem.

**Comment by dustingetz** [comment]
I'm wrong, the test was broken due to my dumb error, apply works fine against stores
