### ISSUE TITLE
Enjoy separated addons - react-addons-update

### ISSUE THREAD

**Issue by lijunle** [dustingetz/react-cursor#67]
As of React 0.14, [each addon is moved to separated package](https://facebook.github.io/react/blog/#two-packages-react-and-react-dom), in this project, install [react-addons-update](https://www.npmjs.com/package/react-addons-update) separatedly and enjoy it.

This is one more step to decouple with React.  :tada:  :tada:  :tada:  :tada:

**Comment by dustingetz** [comment]
Thanks, is there a deprecation warning or is this breaking react-cursor with react 14 right now?

**Comment by lijunle** [comment]
From source:

- [Cursor.js](https://github.com/dustingetz/react-cursor/blob/master/src/Cursor.js) only use `React.addons.update` function.
- Other files does **not** use any React functions.

However, `React.render` is deprecated, and moved to another package [react-dom](https://www.npmjs.com/package/react-dom). Consider to update the PR about decouple React.

**Comment by dustingetz** [comment]
I want both branches of react-cursor (master branch, and the experimental refcursor branch) to work with React 13 - so if nothing is broken, i want to wait a few weeks to address this.

**Comment by lijunle** [comment]
Which is your **experimental refcursor branch*?

**Comment by dustingetz** [comment]
https://github.com/dustingetz/react-cursor/tree/djg/53

**Comment by lijunle** [comment]
BTW, React [declared](http://facebook.github.io/react/blog/#breaking-changes) that, `props` is frozen and cannot be mutated.

> The props object is now frozen, so mutating props after creating a component element is no longer supported. In most cases, React.cloneElement should be used instead. This change makes your components easier to reason about and enables the compiler optimizations mentioned above.

I don't know how they can do it. Please investigate more to support #54.

**Comment by nuclearspike** [comment]
Dustin, I'm interested in trying this project out, but I am interested to know how big of an update it will take to have it work with 0.14 now that props are frozen.

**Comment by dustingetz** [comment]
Hi Paul - react-cursor does not mutate props, so props being frozen has no effect

**Comment by nuclearspike** [comment]
Cool. Thanks for the speedy reply!

**Comment by dustingetz** [comment]
Fixed in 2.0-apha.4

**Comment by dustingetz** [comment]
Our react dependency is now encapsulated by https://github.com/dustingetz/update-in
