### ISSUE TITLE
warning using React 14 dev build

### ISSUE THREAD

**Issue by dustingetz** [dustingetz/react-cursor#70]

**Comment by lijunle** [comment]
What is this issue about?

**Comment by dustingetz** [comment]
Warning: require('react/addons') is deprecated. Access using require('react-addons-{addon}') instead.

Warning is only when used in webpack configuration

**Comment by lijunle** [comment]
The `react-addons-{addons}` can be a drop-in replacement. No other code needs to touch.

**Comment by dustingetz** [comment]
1.x should remain backwards compatible for now so I will just leave the
warning in that branch I suppose

**Comment by dustingetz** [comment]
Fixed in 2.0-alpha.4
