### ISSUE TITLE
Add example as jsfiddle

### ISSUE THREAD

**Issue by dustingetz** [dustingetz/react-cursor#84]
Fork this template: https://jsfiddle.net/dustingetz/xvqzw747/

**Comment by lijunle** [comment]
Is the example using react-cursor as state management? I don't see the clues.

**Comment by dustingetz** [comment]
no

**Comment by dustingetz** [comment]
@lijunle here is a fiddle using cursor (i just made it) https://jsfiddle.net/dustingetz/n9kfc17x/

**Comment by lijunle** [comment]
Is it using cursor V1?

**Comment by dustingetz** [comment]
No, that's v2 Cursor, it is fully backwards compatible though, [here is the adapter code](https://github.com/dustingetz/react-cursor/blob/67f8c62c1063d8b8bb491cba339831533137ca96/src/Cursor.js#L36-L37)

**Comment by dustingetz** [comment]
[Here's a test showing both constructors](https://github.com/dustingetz/react-cursor/blob/272c7c062afa6e4401cb4969ad80de565fc39891/src/__tests__/CursorConstructor.spec.js#L11-L20)

**Comment by lijunle** [comment]
:+1: Have you finalized the basic 2.x implementation? More refactor?

**Comment by dustingetz** [comment]
It's finalized, all outstanding issues are documented as issues

**Comment by lijunle** [comment]
Great, I will spend time to learn the code! Thanks for an awesome package! :clap:

**Comment by dustingetz** [comment]
Start here: https://github.com/dustingetz/update-in/

update-in does all the heavy lifting for cursors. There is a not-production-ready example of cursors in the update-in repo which is like 10 lines. Understand that first.
