### ISSUE TITLE
Problem with fresh npm install

### ISSUE THREAD

**Issue by danielmiladinov** [dustingetz/react-cursor#95]
react-cursor@05ed63a has a problematic fresh npm install 
(`rm -r node_modules; npm install`):

```
danielm@slimpickings react-cursor (master) $ npm i
npm ERR! Darwin 15.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "i"
npm ERR! node v0.12.7
npm ERR! npm  v2.13.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package chai@1.10.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer karma-chai@0.1.0 wants chai@*
npm ERR! peerinvalid Peer sinon-chai@2.8.0 wants chai@>=1.9.2 <4
npm ERR! peerinvalid Peer karma-sinon-chai@1.2.0 wants chai@^3.2.0

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/danielm/IdeaProjects/react-cursor/npm-debug.log
danielm@slimpickings react-cursor (master *) $ 
```

**Comment by dustingetz** [comment]
I cant reproduce this

**Comment by dustingetz** [comment]
Sorry, yes I can, but it is warnings.
dustin@mbp react-cursor (master *+)$ npm -v
3.8.6

**Comment by dustingetz** [comment]
npm WARN karma-sinon-chai@1.2.0 requires a peer of chai@^3.2.0 but none was installed.
npm WARN karma-sinon-chai@1.2.0 requires a peer of lolex@^1.4.0 but none was installed.
npm WARN karma-sinon-chai@1.2.0 requires a peer of sinon@^1.17.2 but none was installed.
npm WARN karma-sinon-chai@1.2.0 requires a peer of sinon-chai@^2.8.0 but none was installed.

**Comment by dustingetz** [comment]
dustin@mbp react-cursor (master)$ npm run test

> react-cursor@2.0.0-alpha.13 test /Users/dustin/src/react-cursor
> karma start

module.js:327
    throw err;
    ^

Error: Cannot find module 'lolex'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.require.resolve (internal/module.js:16:19)
    at framework (/Users/dustin/src/react-cursor/node_modules/karma-sinon-chai/index.js:26:40)
    at Array.invoke (/Users/dustin/src/react-cursor/node_modules/di/lib/injector.js:75:15)
    at get (/Users/dustin/src/react-cursor/node_modules/di/lib/injector.js:48:43)
    at /Users/dustin/src/react-cursor/node_modules/karma/lib/server.js:29:14
    at Array.forEach (native)
    at start (/Users/dustin/src/react-cursor/node_modules/karma/lib/server.js:28:21)
    at invoke (/Users/dustin/src/react-cursor/node_modules/di/lib/injector.js:75:15)
    at Object.exports.start (/Users/dustin/src/react-cursor/node_modules/karma/lib/server.js:307:12)

**Comment by dustingetz** [comment]
dustin@mbp react-cursor (master)$ npm ls lolex
react-cursor@2.0.0-alpha.13 /Users/dustin/src/react-cursor
├── UNMET PEER DEPENDENCY chai@1.10.0
├── UNMET PEER DEPENDENCY lolex@^1.4.0
├── UNMET PEER DEPENDENCY sinon@^1.17.2
└── UNMET PEER DEPENDENCY sinon-chai@^2.8.0

npm ERR! peer dep missing: chai@^3.2.0, required by karma-sinon-chai@1.2.0
npm ERR! peer dep missing: lolex@^1.4.0, required by karma-sinon-chai@1.2.0
npm ERR! peer dep missing: sinon@^1.17.2, required by karma-sinon-chai@1.2.0
npm ERR! peer dep missing: sinon-chai@^2.8.0, required by karma-sinon-chai@1.2.0
npm ERR! code 1

**Comment by dustingetz** [comment]
https://travis-ci.org/dustingetz/react-cursor/jobs/131127337

**Comment by dustingetz** [comment]
fixed the root cause was to just add the missing dependency i think, but i chased my tail for an hour because i changed the babel config before addressing this, so the commit is not clean at all, but the tests work now
